services:
  api:
    image: siq-api
    restart: always
    build: ./api
    # ports:
    #   - '5051:5051'
    # volumes:
    #   - ./api:/app
  frontend:
    image: siq-frontend
    restart: always
    build: ./frontend
    ports:
      - "5173:80"
    # volumes:
    #   - /app/node_modules
    #   - ./frontend:/app
    depends_on:
      - api